name: Java Apps - Run Tests and Package
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test_and_build:
    name: Test and build samples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: run tests
        run: mvn clean test | tee test.log
      - name: build artifacts
        run: mvn clean package -Dmaven.test.skip
      - name: set up artifacts
        run: mkdir artifacts && cp test.log target/*.jar artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: artifacts
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}